// src/components/classData.js

  const classData = {
    10: {
      subjects: [
        "Math",
        "Physics",
        "Chemistry",
        "Biology",
        "English",
        "History",
        "Geography",
        "PoliticalScience",
        "Economics",
      ],
      chapters: {
        Math: [
          "Chapter 1: Real Numbers",
          "Chapter 2: Polynomials",
          "Chapter 3: Pair Of Linear Equations In Two Variables",
          "Chapter 4: Quadratic Equations",
          "Chapter 5: Arithmetic Progressions",
          "Chapter 6: Triangles",
          "Chapter 7: Coordinate Geometry",
          "Chapter 8: Introduction To Trigonometry",
          "Chapter 9: Some Applications Of Trigonometry",
          "Chapter 10: Circles",
          "Chapter 11: Areas Related To Circles",
          "Chapter 12: Surface Areas And Volumes",
          "Chapter 13: Statistics",
          "Chapter 14: Probability",
        ],
        Physics: [
          "CHAPTER 1: Light-Reflection and Refraction",
          "CHAPTER 2:The Human Eye And The Colourful World",
          "CHAPTER 3:Electricity",
          "CHAPTER 4: Magnetic Effects Of Electric Current",
          "CHAPTER 5: Sources Of Energy",
          "CHAPTER 6: Our Environment",
        ],
        Chemistry: [
          "Chapter 1: Chemical Reactions and Equations",
          "Chapter 2: Acids, Bases and Salts",
          "Chapter 3: Metals and Non-metals",
          "Chapter 4: Carbon and its Compounds",
        ],
        Biology: [
          "Chapter 1: Life Process",
          "Chapter 2: Control and Coordination",
          "Chapter 3: Reproduction",
          "Chapter 4: Heredity",
          "Chapter 5: Our Environment",
        ],

        English: [
          "A Letter to God",
          "Nelson Mandela: Long Walk to Freedom",
          "From the Diary of Anne Frank",
          "The Hundred Dresses – I & II",
          "Mijbil the Otter",
          "Madam Rides the Bus",
          "The Sermon at Benares",
          "The Proposal",
          "Dust of Snow",
          "Fire and Ice",
          "A Tiger in the Zoo",
          "How to Tell Wild Animals",
          "The Ball Poem",
          "A Triumph of Surgery",
          "The Midnight Visitor",
          "The Thief’s Story",
          "Bholi",
        ],

        History: [
          "The Rise of Nationalism in Europe",
          "Nationalism in India",
          "The Making of a Global World",
          "The Age of Industrialization",
          "Print Culture and the Modern World",
        ],

        Geography: [
          "Resources and Development",
          "Forest and Wildlife Resources",
          "Water Resources",
          "Agriculture",
          "Minerals and Energy Resources",
          "Manufacturing Industries",
          "Lifelines of National Economy",
        ],

        PoliticalScience: [
          "Power Sharing",
          "Federalism",
          "Gender, Religion and Caste",
          "Political Parties",
          "Outcomes of Democracy",
        ],

        Economics: [
          "Development",
          "Sectors of the Indian Economy",
          "Money and Credit",
          "Globalisation and the Indian Economy",
          "Consumer Rights",
        ],
      },
    },
    11: {
      subjects: [
        "Math",
        "Physics",
        "Chemistry",
        "Botany",
        "Zoology",
        "Genetics",
        "Economics",
      ],
      chapters: {
        Math: [
          "Sets",
          "Relations and Functions",
          "Trigonometric Functions",
          "Complex Numbers",
          "Linear Inequalities",
          "Permutations and Combinations",
          "Binomial Theorem",
          "Sequence and Series",
          "Straight Lines",
          "Conic Sections",
          "Introduction to Three Dimensional Geometry",
          "Limits and Derivatives",
          "Statistics",
          "Probability",
        ],

        Physics: [
          "Physical World",
          "Units and Measurements",
          "Motion in a Straight Line",
          "Motion in a Plane",
          "Laws of Motion",
          "Work, Energy and Power",
          "System of Particles and Rotational Motion",
          "Gravitation",
          "Mechanical Properties of Solids",
          "Mechanical Properties of Fluids",
          "Thermal Properties of Matter",
          "Thermodynamics",
          "Kinetic Theory",
          "Oscillations",
          "Waves",
        ],

        Chemistry: [
          "Some Basic Concepts of Chemistry",
          "Structure of Atom",
          "Classification of Elements",
          "Chemical Bonding",
          "Thermodynamics",
          "Equilibrium",
          "Redox Reactions",
          "General organic chemistry (GOC)",
          "Hydrocarbons",
        ],
        Botany: [
          "The Living World",
          "Biological Classification",
          "Plant Kingdom",
          "Morphology of Flowering Plants",
          "Anatomy of Flowering Plants",
          "Transport in Plants",
          "Mineral Nutrition",
          "Photosynthesis in Higher Plants",
          "Respiration in Plants",
          "Plant Growth and Development",
        ],

        Zoology: [
          "Animal Kingdom",
          "Structural Organisation in Animals",
          "Digestion and Absorption",
          "Breathing and Exchange of Gases",
          "Body Fluids and Circulation",
          "Excretory Products and Their Elimination",
          "Locomotion and Movement",
          "Neural Control and Coordination",
          "Chemical Coordination and Integration",
        ],

        Genetics: [
          // --- Cell Biology and Biomolecules ---
          "Cell: The Unit of Life",
          "Biomolecules",
          "Cell Cycle and Cell Division",
        ],
        Economics: [
          "Introduction to Microeconomics",
          "Consumer's Equilibrium and Demand",
          "Producer Behaviour and Supply",
          "Forms of Market and Price Determination under Perfect Competition with Simple Applications",
          "Introduction to Statistics for Economics",
          "Collection, Organisation and Presentation of Data",
          "Statistical Tools and Interpretation",
        ],
      },
    },
    12: {
      subjects: [
        "Math",
        "Physics",
        "Chemistry",
        "Botany",
        "Zoology",
        "GeneticsAndEvolution",
        "English",
      ],
      chapters: {
        Math: [
          "Relations and Functions",
          "Inverse Trigonometric Functions",
          "Matrices",
          "Determinants",
          "Continuity and Differentiability",
          "Application of Derivatives",
          "Integration",
          "Application of Integral",
          "Differential Equations",
          "Vector Algebra",
          "Three Dimensional Geometry",
          "Linear Programming",
          "Probability",
        ],
        Physics: [
          // --- Electrostatics & Current Electricity ---
          "Electrostatics",
          "Electric Potential and Capacitance",
          "Current Electricity",
          "Moving Charges and Magnetism",
          "Magnetism and Matter",
          "Electromagnetic Induction",
          "Alternating Currents",
          "Ray Optics",
          "Wave Optics",
          "Dual Nature of Matter and Radiation",
          "Atoms",
          "Nuclei",
          "Semiconductor",
        ],

        Chemistry: [
          "Solutions",
          "Electrochemistry",
          "Chemical Kinetics",
          "The d-Block Elements",
          "The Organic Chemistry - Some Basic Principles",
          "Hydrocarbons",
          "Alcohols, Phenols and Ethers",
          "The Chemistry of Aldehydes, Ketones and Carboxylic Acids",
          "Amines",
          "Biomolecules",
        ],
        Botany: [
          "Reproduction in Plants",
          "Plant Growth and Development",
          "Photosynthesis",
          "Respiration in Plants",
          "Transport in Plants",
          "Mineral Nutrition",
          "Plant Hormones",
        ],

        Zoology: [
          "Human Reproduction",
          "Reproductive Health",
          "Human Development",
          "Blood and Circulation",
          "Excretory Products and Their Elimination",
          "Muscle and Movement",
          "Neural Control and Coordination",
          "Chemical Coordination and Integration",
          "Locomotion and Movement",
          "Respiration in Humans",
          "Digestion and Absorption",
          "Breathing and Exchange of Gases",
        ],

        GeneticsAndEvolution: [
          "DNA Replication and Recombination",
          "Structure of Gene and Chromosomes",
          "Mendelian Inheritance",
          "Molecular Genetics",
          "Evolution",
          "Human Genetics and Biotechnology",
          "Biotechnology Principles and Processes",
          "Biotechnology and Its Applications",
        ],
        English: [
          "The Last Lesson",
          "Lost Spring",
          "Deep Water",
          "The Rattrap",
          "Indigo",
          "Poets and Pancakes",
          "The Interview",
          "Going Places",
          "My Mother at Sixty-Six",
          "An Elementary School Classroom in a Slum",
          "Keeping Quiet",
          "A Thing of Beauty",
          "A Roadside Stand",
          "Aunt Jennifer's Tigers",
          "The Third Level",
          "The Tiger King",
          "Journey to the End of the Earth",
          "The Enemy",
          "Should Wizard Hit Mommy?",
          "On the Face of It",
          "Evans Tries an O-Level",
        ],
      },
    },
  };

export default classData;
